<?php
require_once __DIR__ . '/includes/functions.php';

$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? '127.0.0.1');
    $dbName = trim($_POST['db_name'] ?? 'freenetly');
    $dbUser = trim($_POST['db_user'] ?? 'freenetly');
    $dbPass = trim($_POST['db_pass'] ?? 'freenetly');
    $appUrl = trim($_POST['app_url'] ?? 'http://localhost/freenetly');
    $adminLogin = trim($_POST['admin_email'] ?? 'TheAceMotiur');
    $adminPassword = trim($_POST['admin_password'] ?? 'AmiMotiur27@');

    try {
        $server = new mysqli($dbHost, $dbUser, $dbPass);
        if ($server->connect_error) {
            throw new Exception('Could not connect to the database server: ' . $server->connect_error);
        }

        $server->query('CREATE DATABASE IF NOT EXISTS `' . $server->real_escape_string($dbName) . '`');
        $server->select_db($dbName);

        $server->query(
            'CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                full_name VARCHAR(120) NOT NULL,
                email VARCHAR(160) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL DEFAULT "user",
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB'
        );

        $server->query(
            'CREATE TABLE IF NOT EXISTS services (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(120) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT "running",
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY uq_services_name (name)
            ) ENGINE=InnoDB'
        );

        $server->query(
            'CREATE TABLE IF NOT EXISTS user_databases (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT NOT NULL UNIQUE,
                db_name VARCHAR(64) NOT NULL,
                db_user VARCHAR(64) NOT NULL,
                db_password VARCHAR(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB'
        );

        $server->query("INSERT INTO services (name, status) SELECT 'Apache', 'running' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'Apache')");
        $server->query("INSERT INTO services (name, status) SELECT 'PHP', 'running' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'PHP')");
        $server->query("INSERT INTO services (name, status) SELECT 'MySQL', 'running' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'MySQL')");
        $server->query("INSERT INTO services (name, status) SELECT 'phpMyAdmin', 'running' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'phpMyAdmin')");

        $adminHash = password_hash_value($adminPassword);
        $server->query(
            'INSERT INTO users (full_name, email, password_hash, role) VALUES (
                "' . $server->real_escape_string($adminLogin) . '",
                "' . $server->real_escape_string($adminLogin) . '",
                "' . $server->real_escape_string($adminHash) . '",
                "admin"
            ) ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), role = VALUES(role)'
        );

        $configPath = __DIR__ . '/includes/config.php';
        $configContents = <<<PHP
<?php
// Generated by the installer.
define('APP_NAME', 'FreeNetly Control Panel');
define('APP_URL', '{$appUrl}');
define('DB_HOST', '{$dbHost}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');
define('INSTALL_LOCK', '1');
PHP;

        if (file_put_contents($configPath, $configContents) === false) {
            throw new Exception('Could not write the configuration file.');
        }

        $message = 'Installation completed. The admin account is ready and the control panel has been prepared.';
    } catch (Throwable $exception) {
        $error = $exception->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Installer | FreeNetly</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-slate-950 text-slate-100 min-h-screen">
    <div class="max-w-4xl mx-auto px-6 py-16">
      <div class="rounded-3xl border border-slate-800 bg-slate-900/80 p-8 shadow-2xl shadow-cyan-500/10">
        <h1 class="text-3xl font-semibold">One-click installer</h1>
        <p class="mt-3 text-slate-400">Configure the database and create the initial admin account for the panel.</p>

        <?php if ($message): ?>
          <div class="mt-6 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-300"><?= html($message) ?></div>
          <div class="mt-6 flex gap-4">
            <a href="auth/login.php" class="rounded-full bg-cyan-500 px-4 py-2 text-sm font-medium text-slate-950">Open login</a>
            <a href="index.php" class="rounded-full border border-slate-700 px-4 py-2 text-sm font-medium">Back home</a>
          </div>
        <?php endif; ?>

        <?php if ($error): ?>
          <div class="mt-6 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-rose-300"><?= html($error) ?></div>
        <?php endif; ?>

        <?php if (!$message): ?>
        <form method="post" class="mt-8 space-y-4">
          <div class="grid md:grid-cols-2 gap-4">
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Database host</span>
              <input type="text" name="db_host" value="127.0.0.1" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Database name</span>
              <input type="text" name="db_name" value="freenetly" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Database user</span>
              <input type="text" name="db_user" value="freenetly" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Database password</span>
              <input type="password" name="db_pass" value="freenetly" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Application URL</span>
              <input type="text" name="app_url" value="http://localhost/freenetly" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
            <label class="block">
              <span class="mb-2 block text-sm text-slate-400">Admin email</span>
              <input type="text" name="admin_email" value="TheAceMotiur" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
            </label>
          </div>
          <label class="block">
            <span class="mb-2 block text-sm text-slate-400">Admin password</span>
            <input type="password" name="admin_password" value="AmiMotiur27@" class="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" />
          </label>
          <button type="submit" class="rounded-full bg-cyan-500 px-5 py-3 font-medium text-slate-950">Install panel</button>
        </form>
        <?php endif; ?>
      </div>
    </div>
  </body>
</html>
